name: "helm chart create"
description: "This action create an example helm chart"
branding:
  color: green
  icon: shield

inputs:
  ChartName:
    description: "Name of the helm chart"
    required: true
  Path:
    description: "Path in which helm chart is created"
    required: false

runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.ChartName }}
    - ${{ inputs.Path }}}
