name: "helm create command"
description: "execute"
branding:
  color: green
  icon: shield

inputs:
  parameters:
    description: "other parameters in helm create command"
    required: true

runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.parameters }}
